import static fj.data.Option.none;
import org.codehaus.mojo.unix.FileAttributes
import org.codehaus.mojo.unix.UnixFileMode
import static org.codehaus.mojo.unix.UnixFsObject.directory
import static org.codehaus.mojo.unix.UnixFsObject.regularFile
import org.codehaus.mojo.unix.deb.Dpkg
import org.codehaus.mojo.unix.deb.DpkgDebUtil
import org.codehaus.mojo.unix.deb.DpkgDebUtil.ControlFile
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertDebEntries
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertFormat
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertPkgEntries
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertRelaxed
import static org.codehaus.mojo.unix.maven.ShittyUtil.r
import org.codehaus.mojo.unix.sysvpkg.PkgchkUtil
import org.codehaus.mojo.unix.sysvpkg.PkginfoUtil
import org.codehaus.mojo.unix.sysvpkg.PkginfoCommand
import org.codehaus.mojo.unix.sysvpkg.PkginfoUtil.PackageInfo
import org.codehaus.mojo.unix.rpm.RpmUtil
import org.codehaus.mojo.unix.rpm.RpmUtil.SpecFile
import org.codehaus.mojo.unix.rpm.Rpmbuild

boolean success = true

// -----------------------------------------------------------------------
// Deb
// -----------------------------------------------------------------------

assertFormat "deb", "dpkg", Dpkg.available(), {
  File deb = new File((File) basedir, "target/jetty-1.1-2.deb")

  ControlFile controlFile = new ControlFile("devel", "standard", "Trygve Laugstol", "jetty", "1.1-2", "all",
          """Jetty Servlet Container
 Open-source, standards-based, full-featured web server implemented entirely in Java.""")

  success &= assertRelaxed(controlFile, DpkgDebUtil.getControlFile(deb));

  FileAttributes dirAttributes = new FileAttributes(none(), none(), UnixFileMode.fromInt(0755));
  FileAttributes fileAttributes = new FileAttributes(none(), none(), UnixFileMode.fromString("rw-r--r--"));

  success &= assertDebEntries(deb, [
          directory(r("."), none(), dirAttributes),
          directory(r("opt"), none(), dirAttributes),
          directory(r("opt/jetty"), none(), dirAttributes),
          directory(r("opt/jetty/bin"), none(), dirAttributes),
          directory(r("opt/jetty/contexts"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build"), none(), dirAttributes),
          directory(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources"), none(), dirAttributes),
          directory(r("opt/jetty/contexts/test.d"), none(), dirAttributes),
          directory(r("opt/jetty/etc"), none(), dirAttributes),
          directory(r("opt/jetty/javadoc"), none(), dirAttributes),
          directory(r("opt/jetty/lib"), none(), dirAttributes),
          directory(r("opt/jetty/lib/annotations"), none(), dirAttributes),
          directory(r("opt/jetty/lib/cometd"), none(), dirAttributes),
          directory(r("opt/jetty/lib/ext"), none(), dirAttributes),
          directory(r("opt/jetty/lib/grizzly"), none(), dirAttributes),
          directory(r("opt/jetty/lib/jmx"), none(), dirAttributes),
          directory(r("opt/jetty/lib/jndi"), none(), dirAttributes),
          directory(r("opt/jetty/lib/jsp-2.1"), none(), dirAttributes),
          directory(r("opt/jetty/lib/plus"), none(), dirAttributes),
          directory(r("opt/jetty/lib/ssl"), none(), dirAttributes),
          directory(r("opt/jetty/lib/wadi"), none(), dirAttributes),
          directory(r("opt/jetty/lib/win32"), none(), dirAttributes),
          directory(r("opt/jetty/lib/xbean"), none(), dirAttributes),
          directory(r("opt/jetty/LICENSES"), none(), dirAttributes),
          directory(r("opt/jetty/LICENSES/contrib"), none(), dirAttributes),
          directory(r("opt/jetty/logs"), none(), dirAttributes),
          directory(r("opt/jetty/resources"), none(), dirAttributes),
          directory(r("opt/jetty/share"), none(), dirAttributes),
          directory(r("opt/jetty/share/licenses"), none(), dirAttributes),
          directory(r("opt/jetty/share/licenses/contrib"), none(), dirAttributes),
          directory(r("opt/jetty/webapps"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/auth"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/cgi-bin"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/chat"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/js"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/jsp"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/com"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/org"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/lib"), none(), dirAttributes),
          directory(r("opt/jetty/webapps/test/WEB-INF/tags"), none(), dirAttributes),
          directory(r("var"), none(), dirAttributes),
          directory(r("var/opt"), none(), dirAttributes),
          directory(r("var/opt/jetty"), none(), dirAttributes),
          directory(r("var/opt/jetty/cache"), none(), dirAttributes),
          directory(r("var/opt/jetty/log"), none(), dirAttributes),
          directory(r("var/opt/jetty/test-directory"), none(), dirAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-gregw.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-janb.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/ccla-template.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/CDDLv1.0.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-jvz.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-gnodet.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-dyu.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/ccla-sabre.pdf"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-mpurland.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-dexter.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-lorban.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-potterru.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-sbordet.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/contrib/cla-jocsch.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/LICENSE.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-jules.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/ccla-exist.pdf"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-jesse.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/ccla-simulalabs.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-sbordet.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-jfarcand.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/NOTICE.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-template.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-jstrachan.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-tvernum.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/share/licenses/cla-ngonzalez.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jmx/jetty-jmx-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/wadi-core-2.0-M10.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/cglib-nodep-2.1_3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/backport-util-concurrent-2.2.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/wadi-group-2.0-M10.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/jetty-wadi-session-manager-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/slf4j-simple-1.0.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/wadi-aop-2.0-M10.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/jcl104-over-slf4j-1.0.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/aspectjrt-1.5.2a.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/juli-6.0.13.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/concurrent-1.3.4.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/tribes-6.0.13.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/commons-codec-1.2.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/wadi-tribes-2.0-M10.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/commons-httpclient-3.0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/wadi/regexp-1.3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/xbean/jetty-xbean-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jndi/mail-1.4.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jndi/activation-1.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jndi/jetty-jndi-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/grizzly/grizzly-framework-1.7.0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/grizzly/jetty-grizzly-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/win32/wrapper.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/win32/wrapper.dll"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/win32/jetty-win32-service-java-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jetty-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/cometd/cometd-api-1.0.beta1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/cometd/cometd-jetty-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jsp-2.1/jsp-2.1-jetty-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jsp-2.1/jsp-2.1-glassfish-9.1.02.B04.p0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jsp-2.1/core-3.1.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jsp-2.1/jsp-api-2.1-glassfish-9.1.02.B04.p0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jsp-2.1/ant-1.6.5.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/servlet-api-3.0.pre1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/plus/jetty-plus-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/jetty-annotations-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/geronimo-annotation_1.0_spec-1.0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/asm-3.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/geronimo-jta_1.1_spec-1.1.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/servlet-annotation-spec-3.0.pre0.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/asm-commons-3.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/annotations/asm-tree-3.1.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-threadpool-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-rewrite-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-servlet-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-client-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-html-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-ajp-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ext/jetty-servlet-tester-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/ssl/jetty-ssl-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/lib/jetty-util-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/start.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/bin/jetty-service.conf"), none(), 0, fileAttributes),
          // Assert that the default src/main/unix/files copy work
          regularFile(r("opt/jetty/bin/extra-app"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/bin/jetty.sh"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/bin/build_release_bundles.sh"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/bin/Jetty-Service.exe"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-jocsch.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-sbordet.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-jvz.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-potterru.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-dexter.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-lorban.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-mpurland.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/ccla-sabre.pdf"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-dyu.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/LICENSES/contrib/cla-gnodet.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-jmx.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-ajp.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/login.conf"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jdbcRealm.properties"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-plus.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-bio.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-jaas.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/webdefault.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-stats.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/keystore"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-grizzly.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-bio-ssl.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-rewrite.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-proxy.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-ssl.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/realm.properties"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-logging.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/login.properties"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/etc/jetty-win32-service.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/README-unix.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/README.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/javadoc/contents.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts/demo.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts/test.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts/javadoc.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts/test.d/override-web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts/README.TXT"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/VERSION.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/wadi.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme/JNDITest.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/jta.properties"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/jetty-env.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/instruction-web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/instructions.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-jndi.d/index.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/README.TXT"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/index.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/jta.properties"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoAnnotationTest.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoContextListenerTest.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/TestListener.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoFilterTest.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockUserTransaction.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/AnnotationTest.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockDataSource.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/jetty-env.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/cometd.war"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/dat.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/cgi-bin/hello.sh"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/snoop.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/data.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/rewrite.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/js/ajax.js"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/js/behaviour.js"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/js/index.htm"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/auth/relax.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/auth/file.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/da.txt.gz"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/chat/chat.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/chat/chat.css"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/chat/chat.js"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/da.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/index.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jetty_banner.gif"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/data.txt.gz"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/dump.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/bean1.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/tagfile.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/expr.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/tag.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/bean2.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/index.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/jsp/tag2.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/favicon.ico"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Member.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/CookieDump.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/HelloWorld.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestListener.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/CometServlet.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Date2Tag.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/SessionDump.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TagListener.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/DispatchServlet.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$1.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/DateTag.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$2.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Counter.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestFilter.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Message.class"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/lib/jetty-servlet-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/lib/jetty-util-7.0.0pre3.jar"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/jetty-web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/acme-taglib.tld"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/tags/panel.tag"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/WEB-INF/acme-taglib2.tld"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/d.txt"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/logonError.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test/logon.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/README.TXT"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/auth.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/WEB-INF/web.xml"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/index.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/authfail.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/login.html"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/webapps/test-jaas/logout.jsp"), none(), 0, fileAttributes),
          regularFile(r("opt/jetty/resources/log4j.properties"), none(), 0, fileAttributes)
  ])
}

// -----------------------------------------------------------------------
// PKG
// -----------------------------------------------------------------------

assertFormat "PKG", "pkginfo", PkginfoCommand.available (), {
File pkg = new File ((File) basedir, "target/jetty-1.1-2.pkg")

success &= assertRelaxed(
        new PackageInfo("jetty", "Jetty Servlet Container", "application", "all", "1.1-2", "Open-source, standards-based, full-featured web server implemented entirely in Java.", none()),
        PkginfoUtil.getPackageInfoForDevice(pkg));

// Ignore dates for now
success &= assertSysvPkgEntries(pkg, [
        directory("/", "17777777777", "?", "?", none()),
        directory("/opt", "17777777777", "?", "?", none()),
        regularFile("/opt/jetty/README-unix.txt", "0644", "jetty", "jetty", 29, 2190, none()),
        regularFile("/opt/jetty/README.txt", "0644", "jetty", "jetty", 4889, 18386, none()),
        regularFile("/opt/jetty/VERSION.txt", "0644", "jetty", "jetty", 151383, 38716, none()),
        regularFile("/opt/jetty/bin/Jetty-Service.exe", "0755", "jetty", "jetty", 204800, 47770, none()),
        regularFile("/opt/jetty/bin/build_release_bundles.sh", "0755", "jetty", "jetty", 488, 36915, none()),
        regularFile("/opt/jetty/bin/jetty-service.conf", "0755", "jetty", "jetty", 1053, 31289, none()),
        regularFile("/opt/jetty/bin/jetty.sh", "0755", "jetty", "jetty", 17127, 57091, none()),
        regularFile("/opt/jetty/contexts-available/README.TXT", "0644", "jetty", "jetty", 124, 11689, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/AnnotationTest.class", "0644", "jetty", "jetty", 6977, 22406, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockDataSource.class", "0644", "jetty", "jetty", 1608, 8360, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockUserTransaction.class", "0644", "jetty", "jetty", 1183, 58614, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoAnnotationTest.class", "0644", "jetty", "jetty", 3489, 42010, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoContextListenerTest.class", "0644", "jetty", "jetty", 975, 61024, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoFilterTest.class", "0644", "jetty", "jetty", 1399, 33274, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/TestListener.class", "0644", "jetty", "jetty", 2939, 13583, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/jta.properties", "0644", "jetty", "jetty", 4949, 51066, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/jetty-env.xml", "0644", "jetty", "jetty", 471, 37561, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/web.xml", "0644", "jetty", "jetty", 1145, 32458, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.d/index.html", "0644", "jetty", "jetty", 1684, 13201, none()),
        regularFile("/opt/jetty/contexts-available/test-annotations.xml", "0644", "jetty", "jetty", 4863, 53244, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme/JNDITest.class", "0644", "jetty", "jetty", 9349, 12283, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/jta.properties", "0644", "jetty", "jetty", 4949, 51066, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/instruction-web.xml", "0644", "jetty", "jetty", 469, 38993, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/jetty-env.xml", "0644", "jetty", "jetty", 2579, 9899, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/web.xml", "0644", "jetty", "jetty", 2608, 28002, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/index.html", "0644", "jetty", "jetty", 2553, 23721, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.d/instructions.html", "0644", "jetty", "jetty", 2152, 57778, none()),
        regularFile("/opt/jetty/contexts-available/test-jndi.xml", "0644", "jetty", "jetty", 6203, 45093, none()),
        regularFile("/opt/jetty/contexts-available/wadi.xml", "0644", "jetty", "jetty", 3521, 50395, none()),
        regularFile("/opt/jetty/contexts/README.TXT", "0644", "jetty", "jetty", 634, 59082, none()),
        regularFile("/opt/jetty/contexts/demo.xml", "0644", "jetty", "jetty", 464, 39135, none()),
        regularFile("/opt/jetty/contexts/javadoc.xml", "0644", "jetty", "jetty", 983, 15619, none()),
        regularFile("/opt/jetty/contexts/test.d/override-web.xml", "0644", "jetty", "jetty", 1293, 43533, none()),
        regularFile("/opt/jetty/contexts/test.xml", "0644", "jetty", "jetty", 3075, 28500, none()),
        regularFile("/opt/jetty/etc/jdbcRealm.properties", "0644", "jetty", "jetty", 2101, 37860, none()),
        regularFile("/opt/jetty/etc/jetty-ajp.xml", "0644", "jetty", "jetty", 603, 39898, none()),
        regularFile("/opt/jetty/etc/jetty-bio-ssl.xml", "0644", "jetty", "jetty", 1241, 29988, none()),
        regularFile("/opt/jetty/etc/jetty-bio.xml", "0644", "jetty", "jetty", 903, 63409, none()),
        regularFile("/opt/jetty/etc/jetty-grizzly.xml", "0644", "jetty", "jetty", 1168, 21904, none()),
        regularFile("/opt/jetty/etc/jetty-jaas.xml", "0644", "jetty", "jetty", 1440, 37534, none()),
        regularFile("/opt/jetty/etc/jetty-jmx.xml", "0644", "jetty", "jetty", 2408, 42361, none()),
        regularFile("/opt/jetty/etc/jetty-logging.xml", "0644", "jetty", "jetty", 1448, 46230, none()),
        regularFile("/opt/jetty/etc/jetty-plus.xml", "0644", "jetty", "jetty", 3777, 10259, none()),
        regularFile("/opt/jetty/etc/jetty-proxy.xml", "0644", "jetty", "jetty", 2757, 53591, none()),
        regularFile("/opt/jetty/etc/jetty-rewrite.xml", "0644", "jetty", "jetty", 2468, 47899, none()),
        regularFile("/opt/jetty/etc/jetty-ssl.xml", "0644", "jetty", "jetty", 1419, 44355, none()),
        regularFile("/opt/jetty/etc/jetty-stats.xml", "0644", "jetty", "jetty", 880, 60826, none()),
        regularFile("/opt/jetty/etc/jetty-win32-service.xml", "0644", "jetty", "jetty", 1094, 8382, none()),
        regularFile("/opt/jetty/etc/jetty.xml", "0644", "jetty", "jetty", 8997, 12193, none()),
        regularFile("/opt/jetty/etc/keystore", "0644", "jetty", "jetty", 1361, 12969, none()),
        regularFile("/opt/jetty/etc/login.conf", "0644", "jetty", "jetty", 130, 12259, none()),
        regularFile("/opt/jetty/etc/login.properties", "0644", "jetty", "jetty", 15, 1288, none()),
        regularFile("/opt/jetty/etc/realm.properties", "0644", "jetty", "jetty", 741, 63997, none()),
        regularFile("/opt/jetty/etc/webdefault.xml", "0644", "jetty", "jetty", 24643, 12630, none()),
        regularFile("/opt/jetty/javadoc/contents.html", "0644", "jetty", "jetty", 85, 6879, none()),
        regularFile("/opt/jetty/lib/annotations/asm-3.1.jar", "0644", "jetty", "jetty", 43033, 55889, none()),
        regularFile("/opt/jetty/lib/annotations/asm-commons-3.1.jar", "0644", "jetty", "jetty", 32693, 46301, none()),
        regularFile("/opt/jetty/lib/annotations/asm-tree-3.1.jar", "0644", "jetty", "jetty", 21879, 45998, none()),
        regularFile("/opt/jetty/lib/annotations/geronimo-annotation_1.0_spec-1.0.jar", "0644", "jetty", "jetty", 12085, 12041, none()),
        regularFile("/opt/jetty/lib/annotations/geronimo-jta_1.1_spec-1.1.1.jar", "0644", "jetty", "jetty", 16030, 50364, none()),
        regularFile("/opt/jetty/lib/annotations/jetty-annotations-7.0.0pre3.jar", "0644", "jetty", "jetty", 31199, 10297, none()),
        regularFile("/opt/jetty/lib/annotations/servlet-annotation-spec-3.0.pre0.jar", "0644", "jetty", "jetty", 8278, 55341, none()),
        regularFile("/opt/jetty/lib/cometd/cometd-api-1.0.beta1.jar", "0644", "jetty", "jetty", 7186, 47614, none()),
        regularFile("/opt/jetty/lib/cometd/cometd-jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 83050, 12536, none()),
        regularFile("/opt/jetty/lib/ext/jetty-ajp-7.0.0pre3.jar", "0644", "jetty", "jetty", 31405, 44264, none()),
        regularFile("/opt/jetty/lib/ext/jetty-client-7.0.0pre3.jar", "0644", "jetty", "jetty", 63996, 35213, none()),
        regularFile("/opt/jetty/lib/ext/jetty-html-7.0.0pre3.jar", "0644", "jetty", "jetty", 37695, 28818, none()),
        regularFile("/opt/jetty/lib/ext/jetty-rewrite-7.0.0pre3.jar", "0644", "jetty", "jetty", 21205, 21496, none()),
        regularFile("/opt/jetty/lib/ext/jetty-servlet-7.0.0pre3.jar", "0644", "jetty", "jetty", 44928, 62661, none()),
        regularFile("/opt/jetty/lib/ext/jetty-servlet-tester-7.0.0pre3.jar", "0644", "jetty", "jetty", 10252, 17572, none()),
        regularFile("/opt/jetty/lib/ext/jetty-threadpool-7.0.0pre3.jar", "0644", "jetty", "jetty", 6071, 2227, none()),
        regularFile("/opt/jetty/lib/grizzly/grizzly-framework-1.7.0.jar", "0644", "jetty", "jetty", 212272, 9359, none()),
        regularFile("/opt/jetty/lib/grizzly/jetty-grizzly-7.0.0pre3.jar", "0644", "jetty", "jetty", 14768, 24577, none()),
        regularFile("/opt/jetty/lib/jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 532332, 14669, none()),
        regularFile("/opt/jetty/lib/jetty-util-7.0.0pre3.jar", "0644", "jetty", "jetty", 133073, 61558, none()),
        regularFile("/opt/jetty/lib/jmx/jetty-jmx-7.0.0pre3.jar", "0644", "jetty", "jetty", 34358, 8315, none()),
        regularFile("/opt/jetty/lib/jndi/activation-1.1.jar", "0644", "jetty", "jetty", 62983, 38991, none()),
        regularFile("/opt/jetty/lib/jndi/jetty-jndi-7.0.0pre3.jar", "0644", "jetty", "jetty", 29089, 42704, none()),
        regularFile("/opt/jetty/lib/jndi/mail-1.4.jar", "0644", "jetty", "jetty", 388864, 27980, none()),
        regularFile("/opt/jetty/lib/jsp-2.1/ant-1.6.5.jar", "0644", "jetty", "jetty", 1034049, 25846, none()),
        regularFile("/opt/jetty/lib/jsp-2.1/core-3.1.1.jar", "0644", "jetty", "jetty", 3566844, 23522, none()),
        regularFile("/opt/jetty/lib/jsp-2.1/jsp-2.1-glassfish-9.1.02.B04.p0.jar", "0644", "jetty", "jetty", 1023436, 30906, none()),
        regularFile("/opt/jetty/lib/jsp-2.1/jsp-2.1-jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 6339, 15197, none()),
        regularFile("/opt/jetty/lib/jsp-2.1/jsp-api-2.1-glassfish-9.1.02.B04.p0.jar", "0644", "jetty", "jetty", 133567, 49011, none()),
        regularFile("/opt/jetty/lib/plus/jetty-plus-7.0.0pre3.jar", "0644", "jetty", "jetty", 71387, 61801, none()),
        regularFile("/opt/jetty/lib/servlet-api-3.0.pre1.jar", "0644", "jetty", "jetty", 150823, 7127, none()),
        regularFile("/opt/jetty/lib/ssl/jetty-ssl-7.0.0pre3.jar", "0644", "jetty", "jetty", 31373, 17334, none()),
        regularFile("/opt/jetty/lib/wadi/aspectjrt-1.5.2a.jar", "0644", "jetty", "jetty", 115002, 38136, none()),
        regularFile("/opt/jetty/lib/wadi/backport-util-concurrent-2.2.jar", "0644", "jetty", "jetty", 326319, 33637, none()),
        regularFile("/opt/jetty/lib/wadi/cglib-nodep-2.1_3.jar", "0644", "jetty", "jetty", 324238, 23530, none()),
        regularFile("/opt/jetty/lib/wadi/commons-codec-1.2.jar", "0644", "jetty", "jetty", 30085, 1683, none()),
        regularFile("/opt/jetty/lib/wadi/commons-httpclient-3.0.jar", "0644", "jetty", "jetty", 279383, 45438, none()),
        regularFile("/opt/jetty/lib/wadi/concurrent-1.3.4.jar", "0644", "jetty", "jetty", 189284, 60663, none()),
        regularFile("/opt/jetty/lib/wadi/jcl104-over-slf4j-1.0.1.jar", "0644", "jetty", "jetty", 6340, 5994, none()),
        regularFile("/opt/jetty/lib/wadi/jetty-wadi-session-manager-7.0.0pre3.jar", "0644", "jetty", "jetty", 21836, 3732, none()),
        regularFile("/opt/jetty/lib/wadi/juli-6.0.13.jar", "0644", "jetty", "jetty", 17508, 32756, none()),
        regularFile("/opt/jetty/lib/wadi/regexp-1.3.jar", "0644", "jetty", "jetty", 25429, 52854, none()),
        regularFile("/opt/jetty/lib/wadi/slf4j-simple-1.0.1.jar", "0644", "jetty", "jetty", 13873, 39299, none()),
        regularFile("/opt/jetty/lib/wadi/tribes-6.0.13.jar", "0644", "jetty", "jetty", 220005, 10160, none()),
        regularFile("/opt/jetty/lib/wadi/wadi-aop-2.0-M10.jar", "0644", "jetty", "jetty", 87051, 52318, none()),
        regularFile("/opt/jetty/lib/wadi/wadi-core-2.0-M10.jar", "0644", "jetty", "jetty", 422738, 45895, none()),
        regularFile("/opt/jetty/lib/wadi/wadi-group-2.0-M10.jar", "0644", "jetty", "jetty", 62325, 7566, none()),
        regularFile("/opt/jetty/lib/wadi/wadi-tribes-2.0-M10.jar", "0644", "jetty", "jetty", 19158, 2460, none()),
        regularFile("/opt/jetty/lib/win32/jetty-win32-service-java-7.0.0pre3.jar", "0644", "jetty", "jetty", 7020, 60477, none()),
        regularFile("/opt/jetty/lib/win32/wrapper.dll", "0644", "jetty", "jetty", 81920, 8891, none()),
        regularFile("/opt/jetty/lib/win32/wrapper.jar", "0644", "jetty", "jetty", 83820, 15031, none()),
        regularFile("/opt/jetty/lib/xbean/jetty-xbean-7.0.0pre3.jar", "0644", "jetty", "jetty", 7132, 39815, none()),
        regularFile("/opt/jetty/resources/log4j.properties", "0644", "jetty", "jetty", 289, 25830, none()),
        regularFile("/opt/jetty/start.jar", "0644", "jetty", "jetty", 17873, 8129, none()),
        regularFile("/opt/jetty/webapps/README.TXT", "0644", "jetty", "jetty", 697, 63316, none()),
        regularFile("/opt/jetty/webapps/cometd.war", "0644", "jetty", "jetty", 3371389, 48328, none()),
        regularFile("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, none()),
        regularFile("/opt/jetty/webapps/test-jaas/WEB-INF/web.xml", "0644", "jetty", "jetty", 979, 15350, none()),
        regularFile("/opt/jetty/webapps/test-jaas/auth.html", "0644", "jetty", "jetty", 522, 41996, none()),
        regularFile("/opt/jetty/webapps/test-jaas/authfail.html", "0644", "jetty", "jetty", 228, 19395, none()),
        regularFile("/opt/jetty/webapps/test-jaas/index.html", "0644", "jetty", "jetty", 1163, 34271, none()),
        regularFile("/opt/jetty/webapps/test-jaas/login.html", "0644", "jetty", "jetty", 476, 38719, none()),
        regularFile("/opt/jetty/webapps/test-jaas/logout.jsp", "0644", "jetty", "jetty", 399, 31628, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/acme-taglib.tld", "0644", "jetty", "jetty", 755, 61445, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/acme-taglib2.tld", "0644", "jetty", "jetty", 1190, 26896, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Member.class", "0644", "jetty", "jetty", 2923, 37293, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Message.class", "0644", "jetty", "jetty", 1115, 59823, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter.class", "0644", "jetty", "jetty", 7202, 61232, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/CometServlet.class", "0644", "jetty", "jetty", 2551, 16794, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/CookieDump.class", "0644", "jetty", "jetty", 3599, 29894, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Counter.class", "0644", "jetty", "jetty", 653, 26343, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Date2Tag.class", "0644", "jetty", "jetty", 1627, 35725, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/DateTag.class", "0644", "jetty", "jetty", 2345, 59053, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/DispatchServlet.class", "0644", "jetty", "jetty", 6057, 14887, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$1.class", "0644", "jetty", "jetty", 1032, 61851, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$2.class", "0644", "jetty", "jetty", 1564, 36227, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump.class", "0644", "jetty", "jetty", 22326, 31905, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/HelloWorld.class", "0644", "jetty", "jetty", 1770, 44206, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/SessionDump.class", "0644", "jetty", "jetty", 5521, 44161, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TagListener.class", "0644", "jetty", "jetty", 2807, 2840, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestFilter.class", "0644", "jetty", "jetty", 2525, 35352, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestListener.class", "0644", "jetty", "jetty", 3741, 10782, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/jetty-web.xml", "0644", "jetty", "jetty", 667, 58267, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/lib/jetty-servlet-7.0.0pre3.jar", "0644", "jetty", "jetty", 44928, 62661, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/lib/jetty-util-7.0.0pre3.jar", "0644", "jetty", "jetty", 133073, 61558, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/tags/panel.tag", "0644", "jetty", "jetty", 370, 27034, none()),
        regularFile("/opt/jetty/webapps/test/WEB-INF/web.xml", "0644", "jetty", "jetty", 8540, 58969, none()),
        regularFile("/opt/jetty/webapps/test/auth/file.txt", "0644", "jetty", "jetty", 610, 28785, none()),
        regularFile("/opt/jetty/webapps/test/auth/relax.txt", "0644", "jetty", "jetty", 610, 28785, none()),
        regularFile("/opt/jetty/webapps/test/cgi-bin/hello.sh", "0644", "jetty", "jetty", 74, 5985, none()),
        regularFile("/opt/jetty/webapps/test/chat/chat.css", "0644", "jetty", "jetty", 688, 55167, none()),
        regularFile("/opt/jetty/webapps/test/chat/chat.html", "0644", "jetty", "jetty", 4281, 28607, none()),
        regularFile("/opt/jetty/webapps/test/chat/chat.js", "0644", "jetty", "jetty", 3993, 39296, none()),
        regularFile("/opt/jetty/webapps/test/d.txt", "0644", "jetty", "jetty", 610, 28785, none()),
        regularFile("/opt/jetty/webapps/test/da.txt", "0644", "jetty", "jetty", 61000, 58960, none()),
        regularFile("/opt/jetty/webapps/test/da.txt.gz", "0644", "jetty", "jetty", 2565, 41622, none()),
        regularFile("/opt/jetty/webapps/test/dat.txt", "0644", "jetty", "jetty", 244000, 3095, none()),
        regularFile("/opt/jetty/webapps/test/data.txt", "0644", "jetty", "jetty", 610000, 30690, none()),
        regularFile("/opt/jetty/webapps/test/data.txt.gz", "0644", "jetty", "jetty", 25691, 17999, none()),
        regularFile("/opt/jetty/webapps/test/favicon.ico", "0644", "jetty", "jetty", 1150, 10245, none()),
        regularFile("/opt/jetty/webapps/test/index.html", "0644", "jetty", "jetty", 1688, 9376, none()),
        regularFile("/opt/jetty/webapps/test/jetty_banner.gif", "0644", "jetty", "jetty", 65384, 29922, none()),
        regularFile("/opt/jetty/webapps/test/js/ajax.js", "0644", "jetty", "jetty", 5587, 19376, none()),
        regularFile("/opt/jetty/webapps/test/js/behaviour.js", "0644", "jetty", "jetty", 7896, 22056, none()),
        regularFile("/opt/jetty/webapps/test/js/index.htm", "0644", "jetty", "jetty", 40, 3652, none()),
        regularFile("/opt/jetty/webapps/test/jsp/bean1.jsp", "0644", "jetty", "jetty", 466, 40182, none()),
        regularFile("/opt/jetty/webapps/test/jsp/bean2.jsp", "0644", "jetty", "jetty", 466, 40181, none()),
        regularFile("/opt/jetty/webapps/test/jsp/dump.jsp", "0644", "jetty", "jetty", 576, 46492, none()),
        regularFile("/opt/jetty/webapps/test/jsp/expr.jsp", "0644", "jetty", "jetty", 496, 37348, none()),
        regularFile("/opt/jetty/webapps/test/jsp/index.html", "0644", "jetty", "jetty", 352, 27144, none()),
        regularFile("/opt/jetty/webapps/test/jsp/tag.jsp", "0644", "jetty", "jetty", 422, 34069, none()),
        regularFile("/opt/jetty/webapps/test/jsp/tag2.jsp", "0644", "jetty", "jetty", 267, 21588, none()),
        regularFile("/opt/jetty/webapps/test/jsp/tagfile.jsp", "0644", "jetty", "jetty", 1015, 2705, none()),
        regularFile("/opt/jetty/webapps/test/logon.html", "0644", "jetty", "jetty", 504, 40946, none()),
        regularFile("/opt/jetty/webapps/test/logonError.html", "0644", "jetty", "jetty", 279, 22733, none()),
        regularFile("/opt/jetty/webapps/test/rewrite.html", "0644", "jetty", "jetty", 683, 59692, none()),
        regularFile("/opt/jetty/webapps/test/snoop.jsp", "0644", "jetty", "jetty", 3825, 28997, none()),
        directory("/opt/jetty", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/LICENSES", "0755", "jetty", "jetty", none()),
        // This really should be here as the pkg has to include the directory
        // directory("/opt/jetty/LICENSES/contrib", "0755", "jetty", "jetty", none()),
        regularFile("/opt/jetty/LICENSES/contrib/ccla-sabre.pdf", "0644", "jetty", "jetty", 725209, 56115, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-dexter.txt", "0644", "jetty", "jetty", 7072, 42907, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-dyu.txt", "0644", "jetty", "jetty", 7215, 45116, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-gnodet.txt", "0644", "jetty", "jetty", 7008, 36880, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-jocsch.txt", "0644", "jetty", "jetty", 7144, 39617, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-jvz.txt", "0644", "jetty", "jetty", 7056, 41230, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-lorban.txt", "0644", "jetty", "jetty", 7153, 39322, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-mpurland.txt", "0644", "jetty", "jetty", 7305, 62129, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-potterru.txt", "0644", "jetty", "jetty", 7065, 41743, none()),
        regularFile("/opt/jetty/LICENSES/contrib/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, none()),
          // Assert that the default src/main/unix/files copy work
        regularFile("/opt/jetty/bin/extra-app", "0644", "jetty", "jetty", 10, 924, none()),
        regularFile("/opt/jetty/share/licenses/CDDLv1.0.txt", "0644", "jetty", "jetty", 16782, 59272, none()),
        regularFile("/opt/jetty/share/licenses/LICENSE.txt", "0644", "jetty", "jetty", 11358, 60331, none()),
        regularFile("/opt/jetty/share/licenses/NOTICE.txt", "0644", "jetty", "jetty", 1382, 54651, none()),
        regularFile("/opt/jetty/share/licenses/ccla-exist.pdf", "0644", "jetty", "jetty", 27721, 13559, none()),
        regularFile("/opt/jetty/share/licenses/ccla-simulalabs.txt", "0644", "jetty", "jetty", 7668, 27501, none()),
        regularFile("/opt/jetty/share/licenses/ccla-template.txt", "0644", "jetty", "jetty", 8105, 3128, none()),
        regularFile("/opt/jetty/share/licenses/cla-gregw.txt", "0644", "jetty", "jetty", 7045, 40474, none()),
        regularFile("/opt/jetty/share/licenses/cla-janb.txt", "0644", "jetty", "jetty", 7006, 37252, none()),
        regularFile("/opt/jetty/share/licenses/cla-jesse.txt", "0644", "jetty", "jetty", 7061, 41117, none()),
        regularFile("/opt/jetty/share/licenses/cla-jfarcand.txt", "0644", "jetty", "jetty", 7092, 43468, none()),
        regularFile("/opt/jetty/share/licenses/cla-jstrachan.txt", "0644", "jetty", "jetty", 7101, 45409, none()),
        regularFile("/opt/jetty/share/licenses/cla-jules.txt", "0644", "jetty", "jetty", 7099, 45014, none()),
        regularFile("/opt/jetty/share/licenses/cla-ngonzalez.txt", "0644", "jetty", "jetty", 7073, 42728, none()),
        regularFile("/opt/jetty/share/licenses/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, none()),
        regularFile("/opt/jetty/share/licenses/cla-template.txt", "0644", "jetty", "jetty", 6731, 16785, none()),
        regularFile("/opt/jetty/share/licenses/cla-tvernum.txt", "0644", "jetty", "jetty", 7054, 41305, none()),
        directory("/opt/jetty/share/licenses/contrib", "0755", "jetty", "jetty", none()),
        regularFile("/opt/jetty/share/licenses/contrib/ccla-sabre.pdf", "0644", "jetty", "jetty", 725209, 56115, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-dexter.txt", "0644", "jetty", "jetty", 7072, 42907, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-dyu.txt", "0644", "jetty", "jetty", 7215, 45116, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-gnodet.txt", "0644", "jetty", "jetty", 7008, 36880, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-jocsch.txt", "0644", "jetty", "jetty", 7144, 39617, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-jvz.txt", "0644", "jetty", "jetty", 7056, 41230, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-lorban.txt", "0644", "jetty", "jetty", 7153, 39322, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-mpurland.txt", "0644", "jetty", "jetty", 7305, 62129, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-potterru.txt", "0644", "jetty", "jetty", 7065, 41743, none()),
        regularFile("/opt/jetty/share/licenses/contrib/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, none()),
        directory("/opt/jetty/bin", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/contexts/test.d", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/etc", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/javadoc", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/annotations", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/cometd", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/ext", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/grizzly", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/jmx", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/jndi", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/jsp-2.1", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/plus", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/ssl", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/wadi", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/win32", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/lib/xbean", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/logs", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/resources", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/com", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/org", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/lib", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/WEB-INF/tags", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/auth", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/cgi-bin", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/chat", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/js", "0755", "jetty", "jetty", none()),
        directory("/opt/jetty/webapps/test/jsp", "0755", "jetty", "jetty", none()),
        // These are created with a <mkdirs>
        directory("/var/opt/jetty", "0755", "jetty", "jetty", none()),
        directory("/var/opt/jetty/cache", "0755", "jetty", "jetty", none()),
        directory("/var/opt/jetty/log", "0755", "jetty", "jetty", none()),
        // This are created with a <mkdir>
        directory("/var/opt/jetty/test-directory", "0755", "jetty", "jetty", none()),
        installationFile("pkginfo", 236, 0, none()),
        installationFile("preinstall", 34, 0, none()),
        installationFile("postinstall", 204, 0, none()),
        installationFile("preremove", 32, 0, none()),
        installationFile("postremove", 31, 0, none()),
])
}

// -----------------------------------------------------------------------
// RPM
// -----------------------------------------------------------------------

assertFormat "RPM", "rpmbuild", Rpmbuild.available(), {
  File rpm = new File((File) basedir, "target/jetty-1.1-2.rpm")
  expected = new SpecFile("jetty", "1.1", 2, "Jetty Servlet Container", "BSD", "Application/Collectors",
          "Open-source, standards-based, full-featured web server implemented entirely in Java.")
  success &= assertRelaxed(expected, RpmUtil.getSpecFileFromRpm(rpm));
}

return success
