import org.codehaus.mojo.unix.FileAttributes
import org.codehaus.mojo.unix.UnixFileMode
import org.codehaus.mojo.unix.UnixFsObject
import org.codehaus.mojo.unix.dpkg.Dpkg
import org.codehaus.mojo.unix.dpkg.DpkgDebUtil
import org.codehaus.mojo.unix.dpkg.DpkgDebUtil.ControlFile
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertDpkgEntries
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertFormat
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertPkgEntries
import static org.codehaus.mojo.unix.maven.ShittyUtil.assertRelaxed
import static org.codehaus.mojo.unix.maven.ShittyUtil.r
import org.codehaus.mojo.unix.pkg.PkgchkUtil
import org.codehaus.mojo.unix.pkg.PkginfoUtil
import org.codehaus.mojo.unix.pkg.PkginfoCommand
import org.codehaus.mojo.unix.pkg.PkginfoUtil.PackageInfo
import org.codehaus.mojo.unix.rpm.RpmUtil
import org.codehaus.mojo.unix.rpm.RpmUtil.SpecFile
import org.codehaus.mojo.unix.rpm.Rpmbuild

boolean success = true

// -----------------------------------------------------------------------
// Dpkg
// -----------------------------------------------------------------------

assertFormat "DPKG", "dpkg", Dpkg.available(), {
  File deb = new File((File) basedir, "target/jetty-1.1-2.deb")

  ControlFile controlFile = new ControlFile("devel", "standard", "Trygve Laugstol", "jetty", "1.1-2", "all",
          """Jetty Servlet Container
 Open-source, standards-based, full-featured web server implemented entirely in Java.""")

  success &= assertRelaxed(controlFile, DpkgDebUtil.getControlFile(deb));

  FileAttributes dirAttributes = new FileAttributes(null, null, UnixFileMode.fromInt(0755));
  FileAttributes fileAttributes = new FileAttributes(null, null, UnixFileMode.fromString("rw-r--r--"));

  success &= assertDpkgEntries(deb, [
          new UnixFsObject.DirectoryUnixOFsbject(r("."), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/bin"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/contexts/test.d"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/etc"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/javadoc"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/annotations"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/cometd"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/ext"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/grizzly"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/jmx"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/jndi"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/jsp-2.1"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/plus"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/ssl"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/wadi"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/win32"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/lib/xbean"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/LICENSES"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/LICENSES/contrib"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/logs"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/resources"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/share"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/share/licenses"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/share/licenses/contrib"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/auth"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/cgi-bin"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/chat"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/js"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/jsp"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/lib"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/tags"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var/opt"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var/opt/jetty"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var/opt/jetty/cache"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var/opt/jetty/log"), null, dirAttributes),
          new UnixFsObject.DirectoryUnixOFsbject(r("var/opt/jetty/test-directory"), null, dirAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-gregw.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-janb.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/ccla-template.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/CDDLv1.0.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-jvz.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-gnodet.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-dyu.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/ccla-sabre.pdf"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-mpurland.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-dexter.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-lorban.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-potterru.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-sbordet.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/contrib/cla-jocsch.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/LICENSE.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-jules.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/ccla-exist.pdf"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-jesse.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/ccla-simulalabs.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-sbordet.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-jfarcand.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/NOTICE.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-template.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-jstrachan.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-tvernum.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/share/licenses/cla-ngonzalez.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jmx/jetty-jmx-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/wadi-core-2.0-M10.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/cglib-nodep-2.1_3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/backport-util-concurrent-2.2.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/wadi-group-2.0-M10.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/jetty-wadi-session-manager-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/slf4j-simple-1.0.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/wadi-aop-2.0-M10.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/jcl104-over-slf4j-1.0.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/aspectjrt-1.5.2a.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/juli-6.0.13.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/concurrent-1.3.4.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/tribes-6.0.13.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/commons-codec-1.2.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/wadi-tribes-2.0-M10.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/commons-httpclient-3.0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/wadi/regexp-1.3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/xbean/jetty-xbean-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jndi/mail-1.4.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jndi/activation-1.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jndi/jetty-jndi-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/grizzly/grizzly-framework-1.7.0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/grizzly/jetty-grizzly-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/win32/wrapper.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/win32/wrapper.dll"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/win32/jetty-win32-service-java-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jetty-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/cometd/cometd-api-1.0.beta1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/cometd/cometd-jetty-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jsp-2.1/jsp-2.1-jetty-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jsp-2.1/jsp-2.1-glassfish-9.1.02.B04.p0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jsp-2.1/core-3.1.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jsp-2.1/jsp-api-2.1-glassfish-9.1.02.B04.p0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jsp-2.1/ant-1.6.5.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/servlet-api-3.0.pre1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/plus/jetty-plus-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/jetty-annotations-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/geronimo-annotation_1.0_spec-1.0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/asm-3.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/geronimo-jta_1.1_spec-1.1.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/servlet-annotation-spec-3.0.pre0.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/asm-commons-3.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/annotations/asm-tree-3.1.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-threadpool-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-rewrite-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-servlet-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-client-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-html-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-ajp-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ext/jetty-servlet-tester-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/ssl/jetty-ssl-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/lib/jetty-util-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/start.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/bin/jetty-service.conf"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/bin/extra-app"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/bin/jetty.sh"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/bin/build_release_bundles.sh"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/bin/Jetty-Service.exe"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-jocsch.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-sbordet.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-jvz.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-potterru.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-dexter.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-lorban.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-mpurland.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/ccla-sabre.pdf"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-dyu.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/LICENSES/contrib/cla-gnodet.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-jmx.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-ajp.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/login.conf"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jdbcRealm.properties"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-plus.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-bio.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-jaas.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/webdefault.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-stats.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/keystore"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-grizzly.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-bio-ssl.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-rewrite.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-proxy.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-ssl.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/realm.properties"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-logging.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/login.properties"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/etc/jetty-win32-service.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/README-unix.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/README.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/javadoc/contents.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts/demo.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts/test.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts/javadoc.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts/test.d/override-web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts/README.TXT"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/VERSION.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/wadi.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme/JNDITest.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/jta.properties"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/jetty-env.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/WEB-INF/instruction-web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/instructions.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-jndi.d/index.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/README.TXT"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/index.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/jta.properties"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoAnnotationTest.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoContextListenerTest.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/TestListener.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoFilterTest.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockUserTransaction.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/AnnotationTest.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockDataSource.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/contexts-available/test-annotations.d/WEB-INF/jetty-env.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/cometd.war"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/dat.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/cgi-bin/hello.sh"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/snoop.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/data.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/rewrite.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/js/ajax.js"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/js/behaviour.js"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/js/index.htm"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/auth/relax.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/auth/file.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/da.txt.gz"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/chat/chat.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/chat/chat.css"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/chat/chat.js"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/da.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/index.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jetty_banner.gif"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/data.txt.gz"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/dump.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/bean1.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/tagfile.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/expr.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/tag.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/bean2.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/index.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/jsp/tag2.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/favicon.ico"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Member.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/CookieDump.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/HelloWorld.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestListener.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/CometServlet.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Date2Tag.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/SessionDump.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TagListener.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/DispatchServlet.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$1.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/DateTag.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$2.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/Counter.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestFilter.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Message.class"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/lib/jetty-servlet-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/lib/jetty-util-7.0.0pre3.jar"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/jetty-web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/acme-taglib.tld"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/tags/panel.tag"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/WEB-INF/acme-taglib2.tld"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/d.txt"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/logonError.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test/logon.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/README.TXT"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/auth.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/WEB-INF/web.xml"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/index.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/authfail.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/login.html"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/webapps/test-jaas/logout.jsp"), null, 0, fileAttributes),
          new UnixFsObject.FileUnixOFsbject(r("opt/jetty/resources/log4j.properties"), null, 0, fileAttributes)
  ])
}

// -----------------------------------------------------------------------
// PKG
// -----------------------------------------------------------------------

assertFormat "PKG", "pkginfo", PkginfoCommand.available (), {
File pkg = new File ((File) basedir, "target/jetty-1.1-2.pkg")

success &= assertRelaxed(
        new PackageInfo("jetty", "Jetty Servlet Container", "application", "all", "1.1-2", "Open-source, standards-based, full-featured web server implemented entirely in Java.", null),
        PkginfoUtil.getPackageInforForDevice(pkg));

// Ignore dates for now
success &= assertPkgEntries(pkg, [
        new PkgchkUtil.Directory("/", "17777777777", "?", "?", null),
        new PkgchkUtil.Directory("/opt", "17777777777", "?", "?", null),
        new PkgchkUtil.RegularFile("/opt/jetty/README-unix.txt", "0644", "jetty", "jetty", 29, 2190, null),
        new PkgchkUtil.RegularFile("/opt/jetty/README.txt", "0644", "jetty", "jetty", 4889, 18386, null),
        new PkgchkUtil.RegularFile("/opt/jetty/VERSION.txt", "0644", "jetty", "jetty", 151383, 38716, null),
        new PkgchkUtil.RegularFile("/opt/jetty/bin/Jetty-Service.exe", "0755", "jetty", "jetty", 204800, 47770, null),
        new PkgchkUtil.RegularFile("/opt/jetty/bin/build_release_bundles.sh", "0755", "jetty", "jetty", 488, 36915, null),
        new PkgchkUtil.RegularFile("/opt/jetty/bin/jetty-service.conf", "0755", "jetty", "jetty", 1053, 31289, null),
        new PkgchkUtil.RegularFile("/opt/jetty/bin/jetty.sh", "0755", "jetty", "jetty", 17127, 57091, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/README.TXT", "0644", "jetty", "jetty", 124, 11689, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/AnnotationTest.class", "0644", "jetty", "jetty", 6977, 22406, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockDataSource.class", "0644", "jetty", "jetty", 1608, 8360, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/MockUserTransaction.class", "0644", "jetty", "jetty", 1183, 58614, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoAnnotationTest.class", "0644", "jetty", "jetty", 3489, 42010, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoContextListenerTest.class", "0644", "jetty", "jetty", 975, 61024, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/PojoFilterTest.class", "0644", "jetty", "jetty", 1399, 33274, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme/TestListener.class", "0644", "jetty", "jetty", 2939, 13583, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/jta.properties", "0644", "jetty", "jetty", 4949, 51066, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/jetty-env.xml", "0644", "jetty", "jetty", 471, 37561, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/web.xml", "0644", "jetty", "jetty", 1145, 32458, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.d/index.html", "0644", "jetty", "jetty", 1684, 13201, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-annotations.xml", "0644", "jetty", "jetty", 4863, 53244, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme/JNDITest.class", "0644", "jetty", "jetty", 9349, 12283, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/jta.properties", "0644", "jetty", "jetty", 4949, 51066, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/instruction-web.xml", "0644", "jetty", "jetty", 469, 38993, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/jetty-env.xml", "0644", "jetty", "jetty", 2579, 9899, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/web.xml", "0644", "jetty", "jetty", 2608, 28002, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/index.html", "0644", "jetty", "jetty", 2553, 23721, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.d/instructions.html", "0644", "jetty", "jetty", 2152, 57778, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/test-jndi.xml", "0644", "jetty", "jetty", 6203, 45093, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts-available/wadi.xml", "0644", "jetty", "jetty", 3521, 50395, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts/README.TXT", "0644", "jetty", "jetty", 634, 59082, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts/demo.xml", "0644", "jetty", "jetty", 464, 39135, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts/javadoc.xml", "0644", "jetty", "jetty", 983, 15619, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts/test.d/override-web.xml", "0644", "jetty", "jetty", 1293, 43533, null),
        new PkgchkUtil.RegularFile("/opt/jetty/contexts/test.xml", "0644", "jetty", "jetty", 3075, 28500, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jdbcRealm.properties", "0644", "jetty", "jetty", 2101, 37860, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-ajp.xml", "0644", "jetty", "jetty", 603, 39898, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-bio-ssl.xml", "0644", "jetty", "jetty", 1241, 29988, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-bio.xml", "0644", "jetty", "jetty", 903, 63409, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-grizzly.xml", "0644", "jetty", "jetty", 1168, 21904, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-jaas.xml", "0644", "jetty", "jetty", 1440, 37534, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-jmx.xml", "0644", "jetty", "jetty", 2408, 42361, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-logging.xml", "0644", "jetty", "jetty", 1448, 46230, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-plus.xml", "0644", "jetty", "jetty", 3777, 10259, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-proxy.xml", "0644", "jetty", "jetty", 2757, 53591, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-rewrite.xml", "0644", "jetty", "jetty", 2468, 47899, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-ssl.xml", "0644", "jetty", "jetty", 1419, 44355, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-stats.xml", "0644", "jetty", "jetty", 880, 60826, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty-win32-service.xml", "0644", "jetty", "jetty", 1094, 8382, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/jetty.xml", "0644", "jetty", "jetty", 8997, 12193, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/keystore", "0644", "jetty", "jetty", 1361, 12969, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/login.conf", "0644", "jetty", "jetty", 130, 12259, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/login.properties", "0644", "jetty", "jetty", 15, 1288, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/realm.properties", "0644", "jetty", "jetty", 741, 63997, null),
        new PkgchkUtil.RegularFile("/opt/jetty/etc/webdefault.xml", "0644", "jetty", "jetty", 24643, 12630, null),
        new PkgchkUtil.RegularFile("/opt/jetty/javadoc/contents.html", "0644", "jetty", "jetty", 85, 6879, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/asm-3.1.jar", "0644", "jetty", "jetty", 43033, 55889, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/asm-commons-3.1.jar", "0644", "jetty", "jetty", 32693, 46301, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/asm-tree-3.1.jar", "0644", "jetty", "jetty", 21879, 45998, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/geronimo-annotation_1.0_spec-1.0.jar", "0644", "jetty", "jetty", 12085, 12041, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/geronimo-jta_1.1_spec-1.1.1.jar", "0644", "jetty", "jetty", 16030, 50364, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/jetty-annotations-7.0.0pre3.jar", "0644", "jetty", "jetty", 31199, 10297, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/annotations/servlet-annotation-spec-3.0.pre0.jar", "0644", "jetty", "jetty", 8278, 55341, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/cometd/cometd-api-1.0.beta1.jar", "0644", "jetty", "jetty", 7186, 47614, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/cometd/cometd-jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 83050, 12536, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-ajp-7.0.0pre3.jar", "0644", "jetty", "jetty", 31405, 44264, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-client-7.0.0pre3.jar", "0644", "jetty", "jetty", 63996, 35213, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-html-7.0.0pre3.jar", "0644", "jetty", "jetty", 37695, 28818, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-rewrite-7.0.0pre3.jar", "0644", "jetty", "jetty", 21205, 21496, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-servlet-7.0.0pre3.jar", "0644", "jetty", "jetty", 44928, 62661, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-servlet-tester-7.0.0pre3.jar", "0644", "jetty", "jetty", 10252, 17572, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ext/jetty-threadpool-7.0.0pre3.jar", "0644", "jetty", "jetty", 6071, 2227, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/grizzly/grizzly-framework-1.7.0.jar", "0644", "jetty", "jetty", 212272, 9359, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/grizzly/jetty-grizzly-7.0.0pre3.jar", "0644", "jetty", "jetty", 14768, 24577, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 532332, 14669, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jetty-util-7.0.0pre3.jar", "0644", "jetty", "jetty", 133073, 61558, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jmx/jetty-jmx-7.0.0pre3.jar", "0644", "jetty", "jetty", 34358, 8315, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jndi/activation-1.1.jar", "0644", "jetty", "jetty", 62983, 38991, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jndi/jetty-jndi-7.0.0pre3.jar", "0644", "jetty", "jetty", 29089, 42704, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jndi/mail-1.4.jar", "0644", "jetty", "jetty", 388864, 27980, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jsp-2.1/ant-1.6.5.jar", "0644", "jetty", "jetty", 1034049, 25846, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jsp-2.1/core-3.1.1.jar", "0644", "jetty", "jetty", 3566844, 23522, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jsp-2.1/jsp-2.1-glassfish-9.1.02.B04.p0.jar", "0644", "jetty", "jetty", 1023436, 30906, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jsp-2.1/jsp-2.1-jetty-7.0.0pre3.jar", "0644", "jetty", "jetty", 6339, 15197, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/jsp-2.1/jsp-api-2.1-glassfish-9.1.02.B04.p0.jar", "0644", "jetty", "jetty", 133567, 49011, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/plus/jetty-plus-7.0.0pre3.jar", "0644", "jetty", "jetty", 71387, 61801, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/servlet-api-3.0.pre1.jar", "0644", "jetty", "jetty", 150823, 7127, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/ssl/jetty-ssl-7.0.0pre3.jar", "0644", "jetty", "jetty", 31373, 17334, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/aspectjrt-1.5.2a.jar", "0644", "jetty", "jetty", 115002, 38136, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/backport-util-concurrent-2.2.jar", "0644", "jetty", "jetty", 326319, 33637, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/cglib-nodep-2.1_3.jar", "0644", "jetty", "jetty", 324238, 23530, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/commons-codec-1.2.jar", "0644", "jetty", "jetty", 30085, 1683, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/commons-httpclient-3.0.jar", "0644", "jetty", "jetty", 279383, 45438, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/concurrent-1.3.4.jar", "0644", "jetty", "jetty", 189284, 60663, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/jcl104-over-slf4j-1.0.1.jar", "0644", "jetty", "jetty", 6340, 5994, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/jetty-wadi-session-manager-7.0.0pre3.jar", "0644", "jetty", "jetty", 21836, 3732, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/juli-6.0.13.jar", "0644", "jetty", "jetty", 17508, 32756, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/regexp-1.3.jar", "0644", "jetty", "jetty", 25429, 52854, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/slf4j-simple-1.0.1.jar", "0644", "jetty", "jetty", 13873, 39299, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/tribes-6.0.13.jar", "0644", "jetty", "jetty", 220005, 10160, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/wadi-aop-2.0-M10.jar", "0644", "jetty", "jetty", 87051, 52318, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/wadi-core-2.0-M10.jar", "0644", "jetty", "jetty", 422738, 45895, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/wadi-group-2.0-M10.jar", "0644", "jetty", "jetty", 62325, 7566, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/wadi/wadi-tribes-2.0-M10.jar", "0644", "jetty", "jetty", 19158, 2460, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/win32/jetty-win32-service-java-7.0.0pre3.jar", "0644", "jetty", "jetty", 7020, 60477, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/win32/wrapper.dll", "0644", "jetty", "jetty", 81920, 8891, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/win32/wrapper.jar", "0644", "jetty", "jetty", 83820, 15031, null),
        new PkgchkUtil.RegularFile("/opt/jetty/lib/xbean/jetty-xbean-7.0.0pre3.jar", "0644", "jetty", "jetty", 7132, 39815, null),
        new PkgchkUtil.RegularFile("/opt/jetty/resources/log4j.properties", "0644", "jetty", "jetty", 289, 25830, null),
        new PkgchkUtil.RegularFile("/opt/jetty/start.jar", "0644", "jetty", "jetty", 17873, 8129, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/README.TXT", "0644", "jetty", "jetty", 697, 63316, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/cometd.war", "0644", "jetty", "jetty", 3371389, 48328, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/WEB-INF/web.xml", "0644", "jetty", "jetty", 979, 15350, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/auth.html", "0644", "jetty", "jetty", 522, 41996, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/authfail.html", "0644", "jetty", "jetty", 228, 19395, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/index.html", "0644", "jetty", "jetty", 1163, 34271, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/login.html", "0644", "jetty", "jetty", 476, 38719, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test-jaas/logout.jsp", "0644", "jetty", "jetty", 399, 31628, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/acme-taglib.tld", "0644", "jetty", "jetty", 755, 61445, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/acme-taglib2.tld", "0644", "jetty", "jetty", 1190, 26896, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Member.class", "0644", "jetty", "jetty", 2923, 37293, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter\$Message.class", "0644", "jetty", "jetty", 1115, 59823, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/ChatFilter.class", "0644", "jetty", "jetty", 7202, 61232, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/CometServlet.class", "0644", "jetty", "jetty", 2551, 16794, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/CookieDump.class", "0644", "jetty", "jetty", 3599, 29894, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Counter.class", "0644", "jetty", "jetty", 653, 26343, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Date2Tag.class", "0644", "jetty", "jetty", 1627, 35725, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/DateTag.class", "0644", "jetty", "jetty", 2345, 59053, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/DispatchServlet.class", "0644", "jetty", "jetty", 6057, 14887, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$1.class", "0644", "jetty", "jetty", 1032, 61851, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump\$2.class", "0644", "jetty", "jetty", 1564, 36227, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/Dump.class", "0644", "jetty", "jetty", 22326, 31905, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/HelloWorld.class", "0644", "jetty", "jetty", 1770, 44206, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/SessionDump.class", "0644", "jetty", "jetty", 5521, 44161, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TagListener.class", "0644", "jetty", "jetty", 2807, 2840, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestFilter.class", "0644", "jetty", "jetty", 2525, 35352, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/com/acme/TestListener.class", "0644", "jetty", "jetty", 3741, 10782, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources/javadoc.css", "0644", "jetty", "jetty", 1548, 61280, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/jetty-web.xml", "0644", "jetty", "jetty", 667, 58267, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/lib/jetty-servlet-7.0.0pre3.jar", "0644", "jetty", "jetty", 44928, 62661, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/lib/jetty-util-7.0.0pre3.jar", "0644", "jetty", "jetty", 133073, 61558, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/tags/panel.tag", "0644", "jetty", "jetty", 370, 27034, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/WEB-INF/web.xml", "0644", "jetty", "jetty", 8540, 58969, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/auth/file.txt", "0644", "jetty", "jetty", 610, 28785, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/auth/relax.txt", "0644", "jetty", "jetty", 610, 28785, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/cgi-bin/hello.sh", "0644", "jetty", "jetty", 74, 5985, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/chat/chat.css", "0644", "jetty", "jetty", 688, 55167, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/chat/chat.html", "0644", "jetty", "jetty", 4281, 28607, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/chat/chat.js", "0644", "jetty", "jetty", 3993, 39296, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/d.txt", "0644", "jetty", "jetty", 610, 28785, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/da.txt", "0644", "jetty", "jetty", 61000, 58960, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/da.txt.gz", "0644", "jetty", "jetty", 2565, 41622, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/dat.txt", "0644", "jetty", "jetty", 244000, 3095, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/data.txt", "0644", "jetty", "jetty", 610000, 30690, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/data.txt.gz", "0644", "jetty", "jetty", 25691, 17999, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/favicon.ico", "0644", "jetty", "jetty", 1150, 10245, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/index.html", "0644", "jetty", "jetty", 1688, 9376, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jetty_banner.gif", "0644", "jetty", "jetty", 65384, 29922, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/js/ajax.js", "0644", "jetty", "jetty", 5587, 19376, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/js/behaviour.js", "0644", "jetty", "jetty", 7896, 22056, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/js/index.htm", "0644", "jetty", "jetty", 40, 3652, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/bean1.jsp", "0644", "jetty", "jetty", 466, 40182, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/bean2.jsp", "0644", "jetty", "jetty", 466, 40181, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/dump.jsp", "0644", "jetty", "jetty", 576, 46492, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/expr.jsp", "0644", "jetty", "jetty", 496, 37348, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/index.html", "0644", "jetty", "jetty", 352, 27144, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/tag.jsp", "0644", "jetty", "jetty", 422, 34069, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/tag2.jsp", "0644", "jetty", "jetty", 267, 21588, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/jsp/tagfile.jsp", "0644", "jetty", "jetty", 1015, 2705, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/logon.html", "0644", "jetty", "jetty", 504, 40946, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/logonError.html", "0644", "jetty", "jetty", 279, 22733, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/rewrite.html", "0644", "jetty", "jetty", 683, 59692, null),
        new PkgchkUtil.RegularFile("/opt/jetty/webapps/test/snoop.jsp", "0644", "jetty", "jetty", 3825, 28997, null),
        new PkgchkUtil.Directory("/opt/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/LICENSES", "0755", "jetty", "jetty", null),
        // This really should be here as the pkg has to include the directory
        // new PkgchkUtil.Directory("/opt/jetty/LICENSES/contrib", "0755", "jetty", "jetty", null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/ccla-sabre.pdf", "0644", "jetty", "jetty", 725209, 56115, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-dexter.txt", "0644", "jetty", "jetty", 7072, 42907, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-dyu.txt", "0644", "jetty", "jetty", 7215, 45116, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-gnodet.txt", "0644", "jetty", "jetty", 7008, 36880, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-jocsch.txt", "0644", "jetty", "jetty", 7144, 39617, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-jvz.txt", "0644", "jetty", "jetty", 7056, 41230, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-lorban.txt", "0644", "jetty", "jetty", 7153, 39322, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-mpurland.txt", "0644", "jetty", "jetty", 7305, 62129, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-potterru.txt", "0644", "jetty", "jetty", 7065, 41743, null),
        new PkgchkUtil.RegularFile("/opt/jetty/LICENSES/contrib/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, null),
        new PkgchkUtil.RegularFile("/opt/jetty/bin/extra-app", "0644", "jetty", "jetty", 10, 924, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/CDDLv1.0.txt", "0644", "jetty", "jetty", 16782, 59272, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/LICENSE.txt", "0644", "jetty", "jetty", 11358, 60331, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/NOTICE.txt", "0644", "jetty", "jetty", 1382, 54651, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/ccla-exist.pdf", "0644", "jetty", "jetty", 27721, 13559, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/ccla-simulalabs.txt", "0644", "jetty", "jetty", 7668, 27501, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/ccla-template.txt", "0644", "jetty", "jetty", 8105, 3128, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-gregw.txt", "0644", "jetty", "jetty", 7045, 40474, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-janb.txt", "0644", "jetty", "jetty", 7006, 37252, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-jesse.txt", "0644", "jetty", "jetty", 7061, 41117, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-jfarcand.txt", "0644", "jetty", "jetty", 7092, 43468, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-jstrachan.txt", "0644", "jetty", "jetty", 7101, 45409, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-jules.txt", "0644", "jetty", "jetty", 7099, 45014, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-ngonzalez.txt", "0644", "jetty", "jetty", 7073, 42728, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-template.txt", "0644", "jetty", "jetty", 6731, 16785, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/cla-tvernum.txt", "0644", "jetty", "jetty", 7054, 41305, null),
        new PkgchkUtil.Directory("/opt/jetty/share/licenses/contrib", "0755", "jetty", "jetty", null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/ccla-sabre.pdf", "0644", "jetty", "jetty", 725209, 56115, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-dexter.txt", "0644", "jetty", "jetty", 7072, 42907, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-dyu.txt", "0644", "jetty", "jetty", 7215, 45116, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-gnodet.txt", "0644", "jetty", "jetty", 7008, 36880, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-jocsch.txt", "0644", "jetty", "jetty", 7144, 39617, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-jvz.txt", "0644", "jetty", "jetty", 7056, 41230, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-lorban.txt", "0644", "jetty", "jetty", 7153, 39322, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-mpurland.txt", "0644", "jetty", "jetty", 7305, 62129, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-potterru.txt", "0644", "jetty", "jetty", 7065, 41743, null),
        new PkgchkUtil.RegularFile("/opt/jetty/share/licenses/contrib/cla-sbordet.txt", "0644", "jetty", "jetty", 7004, 38090, null),
        new PkgchkUtil.Directory("/opt/jetty/bin", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-annotations.d/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts-available/test-jndi.d/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/contexts/test.d", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/etc", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/javadoc", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/annotations", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/cometd", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/ext", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/grizzly", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/jmx", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/jndi", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/jsp-2.1", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/plus", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/ssl", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/wadi", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/win32", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/lib/xbean", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/logs", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/resources", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test-jaas/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/com", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/com/acme", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/org", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/classes/org/mortbay/jetty/build/resources", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/lib", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/WEB-INF/tags", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/auth", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/cgi-bin", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/chat", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/js", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/opt/jetty/webapps/test/jsp", "0755", "jetty", "jetty", null),
        // These are created with a <mkdirs>
        new PkgchkUtil.Directory("/var/opt/jetty", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/var/opt/jetty/cache", "0755", "jetty", "jetty", null),
        new PkgchkUtil.Directory("/var/opt/jetty/log", "0755", "jetty", "jetty", null),
        // This are created with a <mkdir>
        new PkgchkUtil.Directory("/var/opt/jetty/test-directory", "0755", "jetty", "jetty", null),
        new PkgchkUtil.InstallationFile("pkginfo", 236, 0, null),
        new PkgchkUtil.InstallationFile("preinstall", 34, 0, null),
        new PkgchkUtil.InstallationFile("postinstall", 204, 0, null),
        new PkgchkUtil.InstallationFile("preremove", 32, 0, null),
        new PkgchkUtil.InstallationFile("postremove", 31, 0, null),
])
}

// -----------------------------------------------------------------------
// RPM
// -----------------------------------------------------------------------

assertFormat "RPM", "rpmbuild", Rpmbuild.available(), {
  File rpm = new File((File) basedir, "target/jetty-1.1-2.rpm")
  expected = new SpecFile("jetty", "1.1", 2, "Jetty Servlet Container", "BSD", "Application/Collectors",
          "Open-source, standards-based, full-featured web server implemented entirely in Java.")
  success &= assertRelaxed(expected, RpmUtil.getSpecFileFromRpm(rpm));
}

return success
