#!/bin/sh

set -e
  
case "$1" in
  configure)
	  if ! id jetty > /dev/null 2>&1 ; then
      adduser --system --home /usr/share/jetty7 --no-create-home \
		    --ingroup nogroup --disabled-password --shell /bin/false \
		    jetty
	  fi

    common_post_install
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
	  echo "$0 called with unknown argument \`$1'" >&2
	  exit 1
  ;;
esac
