#!/bin/sh

set -e

# Remove cached files
rm -rf /var/cache/jetty7/*

case "$1" in
  purge)
	  userdel jetty || true
    rm -rf /var/log/jetty7
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    # Nothing to do here
  ;;

  *)
    echo "$0 called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac
